### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by aliir74** [consbio/mbgl-renderer#24]
Hi all.
I try to use mbgl-renderer with node API but I couldn't import this module. I try node version of 4, 6 and 10 but none of them didn't work correctly in the importing line.

__node v10.15.0:__
```
/home/ali/Programming/map/TileProvider/node2.js:1
(function (exports, require, module, __filename, __dirname) { import render from 'mbgl-renderer'
                                                                     ^^^^^^

SyntaxError: Unexpected identifier
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInThisContext (vm.js:303:10)
    at Module._compile (internal/modules/cjs/loader.js:657:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:283:19)
```

__node v4.9.1:__
```
/home/ali/Programming/map/TileProvider/node2.js:1
(function (exports, require, module, __filename, __dirname) { import render from 'mbgl-renderer'
                                                              ^^^^^^

SyntaxError: Unexpected reserved word
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:140:18)
    at node.js:1043:3
```

__node v6.16.0:__
```
/home/ali/Programming/map/TileProvider/node2.js:1
(function (exports, require, module, __filename, __dirname) { import render from 'mbgl-renderer'
                                                              ^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.runMain (module.js:611:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:160:9)
```

I use your code example

**Comment by brendan-ward** [comment]
@aliir74 we only targeted the latest LTS versions of node: 8, 10 - so I wouldn't expect <8 to work.

All our examples assume use of `babel` to support things like the `import` statement.  Apologies for not making that more clear in the documentation.  I'll add a bit more information now.

**Comment by aliir74** [comment]
@brendan-ward I cloned your git project and `yarn install` in node v10 LTS. but the same error happened:
```
➜  mbgl-renderer git:(master) ✗ node node-simple.js
/home/ali/Downloads/mbgl-renderer/node-simple.js:1
(function (exports, require, module, __filename, __dirname) { import render from 'mbgl-renderer'
                                                                     ^^^^^^

SyntaxError: Unexpected identifier
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInThisContext (vm.js:303:10)
    at Module._compile (internal/modules/cjs/loader.js:657:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:283:19)
```

**Comment by brendan-ward** [comment]
@aliir74 You need to use `babel` in order to use ES6 `import` commands from the example in our README.

To replicate your example, install `babel-node`: https://babeljs.io/docs/en/babel-node

then on your command line `babel-node node-simple.js`
