### ISSUE TITLE
The CLI seems to be broken by a new version of `babel`

### ISSUE THREAD

**Issue by nikmolnar** [consbio/mbgl-renderer#32]
Attempting to use the CLI results in the following error:

```
Error: Cannot find module '@babel/runtime/helpers/builtin/interopRequireDefault'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.resolve (internal/module.js:18:19)
    at Object.require (/tmp/programs/server/boot.js:288:32)
    at makeInstallerOptions.fallback (packages/modules-runtime.js:604:18)
```

After some research, the problem is likely related to meteor/meteor#10128.

**Comment by brendan-ward** [comment]
This has been resolved
