### ISSUE TITLE
libEGL.so not found

### ISSUE THREAD

**Issue by srinivasrk** [consbio/mbgl-renderer#59]
I tried following the getting started instructions and looks like I'm running into an issue:
```
return process.dlopen(module, path._makeLong(filename));
Error: libEGL.so.1: cannot open shared object file: No such file or directory
at Object.Module._extensions..node (module.js:681:18)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/mbgl-renderer/node_modules/@mapbox/mapbox-gl-native/platform/node/index.js:5:12)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
```

I have tried using the dockerized version as well and run into same issue.

**Comment by srinivasrk** [comment]
` sudo apt install libegl1-mesa libegl1 libgbm-dev libllvm3.9 libprotobuf-dev libxxf86vm-dev xvfb x11-utils`
This helped!
